<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WorkplaceStudent Sign In</name>
   <tag></tag>
   <elementGuidId>380bcc58-7d9c-41bd-90b0-93c503cbad6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='portal-login-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#portal-login-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84b9bff4-6e75-4546-ad84-c9c216aaaa74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>portal-login-button</value>
      <webElementGuid>d0bfad9b-670a-4b6e-b097-c9e2683c5fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/login/</value>
      <webElementGuid>c4ab44b3-4bcf-455e-9d6b-f00ede3a971a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-audience</name>
      <type>Main</type>
      <value>employee</value>
      <webElementGuid>6f7626a4-7e65-415c-a2ac-37bfaeb1f482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workplace/Student Sign In</value>
      <webElementGuid>8f3fa1d6-e5c4-442a-9361-1a3e8820201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portal-login-button&quot;)</value>
      <webElementGuid>c71e6dd1-60eb-4c1e-9129-58e2c6c765c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='portal-login-button']</value>
      <webElementGuid>7c9bfc5b-cb05-4eb5-9df8-61156eca2111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content-wrap']/section/div/div/div[2]/p/a</value>
      <webElementGuid>670d2fd0-dc47-4198-9235-bcb08c1a4d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Workplace/Student Sign In')]</value>
      <webElementGuid>4cb33723-a639-47b3-b82b-d8c86d2ce2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to myUVU'])[1]/following::a[1]</value>
      <webElementGuid>35778cff-4a6f-4cb5-beec-07c194be889d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot my password'])[1]/preceding::a[1]</value>
      <webElementGuid>529639fa-91eb-41c6-8260-8232fc1b0b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage password recovery options'])[1]/preceding::a[2]</value>
      <webElementGuid>114d3988-6ab2-4e03-a1e4-04d5f55e5f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Workplace/Student Sign In']/parent::*</value>
      <webElementGuid>fca5a679-d71a-461b-a06d-957a6090435c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/user/login/')]</value>
      <webElementGuid>87f448e9-5336-49a3-820a-1478d59423ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>08a22398-6c7f-47b1-af5f-48d322e07d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'portal-login-button' and @href = '/user/login/' and (text() = 'Workplace/Student Sign In' or . = 'Workplace/Student Sign In')]</value>
      <webElementGuid>c38b85af-4611-4e4e-8884-51a37ede6c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
